ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - init: >
      composer update --no-interaction &&
      cp .gitpod/blt.yml blt/local.blt.yml &&
      find docroot/sites/ -name 'local*' | xargs rm &&
      blt blt:telemetry:disable --no-interaction &&
      blt settings &&
      sed -i 's/\/https:\/\//\/8001-/g' docroot/sites/default/local.drush.yml &&
      drush si stanford_profile -y
    command: |
      apache2ctl restart
      drush uli
      drush uli | xargs gp preview --external
      git config core.fileMode false
      blt blt:telemetry:disable --no-interaction
