ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: open-preview
    visibility: public
image: pookmish/drupal8ci:gitpod
tasks:
  - before: >
      eval $(command gp env -e) &&
      mkdir -p ~/.ssh &&
      [[ ! -z $SSH_PUBLIC_KEY  ]] &&
      echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      [[ ! -z $SSH_PRIVATE_KEY  ]] &&
      echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa &&
      chmod 600 ~/.ssh/id_rsa &&
      [[ ! -z $GITCONFIG  ]] &&
      echo $GITCONFIG | base64 -d > ~/.gitconfig &&
      chmod 644 ~/.gitconfig
    init: >
      composer update --no-interaction &&
      cp .gitpod/blt.yml blt/local.blt.yml &&
      mkdir -p docroot/sites/settings &&
      cp .gitpod/global.settings.php docroot/sites/settings/global.settings.php &&
      find docroot/sites/ -name 'local*' | xargs rm &&
      blt blt:telemetry:disable --no-interaction &&
      blt settings &&
      sed -i 's/\/https:\/\//\/8001-/g' docroot/sites/default/local.drush.yml &&
      drush si stanford_profile -y
    command: |
      apache2ctl restart
      drush uli
      drush uli | xargs gp preview --external
      git config core.fileMode false
      blt blt:telemetry:disable --no-interaction
